version: '3.4'

services:
  backend-development:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    image: backend-image-development
    container_name: tcah-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '8000:8000'
    volumes:
      - ./backend/:/app
    links:
      - local-db

  local-db:
    container_name: tcah-db
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

  frontend-development:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    image: frontend-image-development
    command: npm start
    ports:
      - "3000:3000"
    links:
      - backend-development
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    env_file:
      - ./frontend/.env

volumes:
  postgres:
    driver: local

networks:
  tcah:
    driver: bridge